# Generated by Django 3.1.5 on 2021-02-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20210217_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='reponse',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
