# Generated by Django 3.1.5 on 2021-02-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_question_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='centre_vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_centre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='date_vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_v', models.DateTimeField(null=True)),
                ('nombre_passion', models.IntegerField(null=True)),
                ('nom_centre', models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.centre_vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='pation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName_Pation', models.CharField(max_length=300)),
                ('cin', models.CharField(max_length=20)),
                ('date_expiration', models.DateTimeField()),
                ('email', models.CharField(max_length=300, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('Statue', models.CharField(choices=[('non_inscrit', 'no_inscrit'), ('inscrit', 'inscrit'), ('vacciné', 'vacciné')], max_length=200)),
                ('date_faccination1', models.DateTimeField(null=True)),
                ('date_faccination2', models.DateTimeField(null=True)),
                ('nom_centre', models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.centre_vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='ville',
            fields=[
                ('nom_ville', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='individue',
        ),
        migrations.AddField(
            model_name='pation',
            name='nom_ville',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.ville'),
        ),
        migrations.AddField(
            model_name='centre_vaccination',
            name='nom_ville',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.ville'),
        ),
    ]
