# Generated by Django 3.1.5 on 2021-02-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0007_auto_20210218_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre_vaccination',
            name='nom_ville',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.ville'),
        ),
        migrations.AlterField(
            model_name='date_vaccination',
            name='date_v',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date_vaccination',
            name='nom_centre',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.centre_vaccination'),
        ),
        migrations.AlterField(
            model_name='date_vaccination',
            name='nombre_passion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pation',
            name='date_faccination1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pation',
            name='date_faccination2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pation',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pation',
            name='nom_centre',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.centre_vaccination'),
        ),
        migrations.AlterField(
            model_name='pation',
            name='nom_ville',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.ville'),
        ),
        migrations.AlterField(
            model_name='pation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
