# Generated by Django 3.1.5 on 2021-02-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0008_auto_20210218_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pation',
            name='Statue',
            field=models.CharField(choices=[('non_inscrit', 'non_inscrit'), ('inscrit', 'inscrit'), ('vacciné', 'vacciné')], max_length=200),
        ),
    ]
