# Generated by Django 3.1.5 on 2021-02-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0011_auto_20210219_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_vaccination',
            name='date_v',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pation',
            name='date_expiration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pation',
            name='date_faccination1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pation',
            name='date_faccination2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
